on:
  push:
    branches:
      - main

name: CD

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY_EZE }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL_EZE }}
          usedocker: true
        env:
          HD_MUSIC_SERVICE_API_KEY: ${{ secrets.MUSIC_SERVICE_API_KEY }}
          HD_USERS_SERVICE_API_KEY: ${{ secrets.USERS_SERVICE_API_KEY }}
          HD_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          HD_DD_API_KEY: ${{ secrets.DD_API_KEY }}
          HD_NODE_ENV: prod
